### ISSUE TITLE
As an authorized User, I want to update my e-mail address

### ISSUE THREAD

**Issue by timur-friedman** [EdgeNet-project/edgenet-legacy-2024#96]
As an authorized user, I wish to be able to change my email address.

## Acceptance Criteria

- A user who changed the email address should be deactivated
- An email verification procedure needs to take place again

### Backend:
- [x] Update the user custom controller
  - [x] Detect if the email address changed
  - [x] Deactivate user in case of email address updated
  - [x] Send an email to verify new email address
  - [x] Activate user if the verification is done
- [x] Code error handling

## To-do
Edit roles to allow an updating email address, which requires a CRD development.
